spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      max-wait: 60000
      initial-size: 1
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/demo